// <auto-generated />
using System;
using FamTec.Server.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamTec.Server.Migrations
{
    [DbContext(typeof(WorksContext))]
    partial class WorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("FamTec.Shared.Model.AdminPlaceTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<int?>("AdminTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ADMIN_TB_ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PLACE_ID");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminTbId" }, "fk_ADMIN_TB_has_PLACE_ADMIN_TB1_idx");

                    b.HasIndex(new[] { "PlaceId" }, "fk_ADMIN_TB_has_PLACE_PLACE1_idx");

                    b.ToTable("admin_place_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.AdminTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("DepartmentTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DEPARTMENT_TB_ID");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TYPE");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.Property<int?>("UserTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("USER_TB_ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentTbId" }, "fk_ADMIN_TB_DEPARTMENT_TB1_idx");

                    b.HasIndex(new[] { "UserTbId" }, "fk_ADMIN_TB_USER_TB_idx");

                    b.ToTable("admin_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.BuildingTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<int?>("BasementFloorNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("BASEMENT_FLOOR_NUM");

                    b.Property<float?>("BasementHeight")
                        .HasColumnType("float")
                        .HasColumnName("BASEMENT_HEIGHT");

                    b.Property<float?>("Boiler")
                        .HasColumnType("float")
                        .HasColumnName("BOILER");

                    b.Property<float?>("BuildingArea")
                        .HasColumnType("float")
                        .HasColumnName("BUILDING_AREA");

                    b.Property<string>("BuildingCd")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BUILDING_CD");

                    b.Property<float?>("BuildingHeight")
                        .HasColumnType("float")
                        .HasColumnName("BUILDING_HEIGHT");

                    b.Property<string>("BuildingStruct")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BUILDING_STRUCT");

                    b.Property<int?>("CargoLiftNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("CARGO_LIFT_NUM");

                    b.Property<DateTime?>("CompletionDt")
                        .HasColumnType("datetime")
                        .HasColumnName("COMPLETION_DT");

                    b.Property<string>("ConstComp")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CONST_COMP");

                    b.Property<float?>("CoolCapacity")
                        .HasColumnType("float")
                        .HasColumnName("COOL_CAPACITY");

                    b.Property<float?>("CoolHeatCapacity")
                        .HasColumnType("float")
                        .HasColumnName("COOL_HEAT_CAPACITY");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<float?>("ElecCapacity")
                        .HasColumnType("float")
                        .HasColumnName("ELEC_CAPACITY");

                    b.Property<float?>("ElevWaterCapacity")
                        .HasColumnType("float")
                        .HasColumnName("ELEV_WATER_CAPACITY");

                    b.Property<float?>("FaucetCapacity")
                        .HasColumnType("float")
                        .HasColumnName("FAUCET_CAPACITY");

                    b.Property<string>("FireRating")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FIRE_RATING");

                    b.Property<int?>("FloorNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("FLOOR_NUM");

                    b.Property<float?>("GasCapacity")
                        .HasColumnType("float")
                        .HasColumnName("GAS_CAPACITY");

                    b.Property<float?>("GenerationCapacity")
                        .HasColumnType("float")
                        .HasColumnName("GENERATION_CAPACITY");

                    b.Property<float?>("GrossFloorArea")
                        .HasColumnType("float")
                        .HasColumnName("GROSS_FLOOR_AREA");

                    b.Property<float?>("GroundArea")
                        .HasColumnType("float")
                        .HasColumnName("GROUND_AREA");

                    b.Property<int?>("GroundFloorNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("GROUND_FLOOR_NUM");

                    b.Property<float?>("GroundHeight")
                        .HasColumnType("float")
                        .HasColumnName("GROUND_HEIGHT");

                    b.Property<float?>("HeatCapacity")
                        .HasColumnType("float")
                        .HasColumnName("HEAT_CAPACITY");

                    b.Property<int?>("InnerParkingNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("INNER_PARKING_NUM");

                    b.Property<float?>("LandArea")
                        .HasColumnType("float")
                        .HasColumnName("LAND_AREA");

                    b.Property<float?>("LandscapeArea")
                        .HasColumnType("float")
                        .HasColumnName("LANDSCAPE_AREA");

                    b.Property<int?>("LiftNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("LIFT_NUM");

                    b.Property<int?>("MenToiletNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("MEN_TOILET_NUM");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<int?>("OuterParkingNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("OUTER_PARKING_NUM");

                    b.Property<int?>("ParkingNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("PARKING_NUM");

                    b.Property<int?>("PeopleLiftNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("PEOPLE_LIFT_NUM");

                    b.Property<int?>("PlaceTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PLACE_TB_ID");

                    b.Property<string>("RoofStruct")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ROOF_STRUCT");

                    b.Property<float?>("RooftopArea")
                        .HasColumnType("float")
                        .HasColumnName("ROOFTOP_AREA");

                    b.Property<float?>("SepticTankCapacity")
                        .HasColumnType("float")
                        .HasColumnName("SEPTIC_TANK_CAPACITY");

                    b.Property<string>("Tel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TEL");

                    b.Property<int?>("ToiletNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("TOILET_NUM");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.Property<string>("Usage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USAGE");

                    b.Property<float?>("WaterCapacity")
                        .HasColumnType("float")
                        .HasColumnName("WATER_CAPACITY");

                    b.Property<float?>("WaterDispenser")
                        .HasColumnType("float")
                        .HasColumnName("WATER_DISPENSER");

                    b.Property<float?>("WaterTank")
                        .HasColumnType("float")
                        .HasColumnName("WATER_TANK");

                    b.Property<int?>("WomenToiletNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("WOMEN_TOILET_NUM");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlaceTbId" }, "fk_BUILDING_TB_PLACE_TB1_idx");

                    b.ToTable("building_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.DepartmentTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("department_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.EnergyMonthUsageTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<float?>("Apr")
                        .HasColumnType("float")
                        .HasColumnName("APR");

                    b.Property<float?>("Aug")
                        .HasColumnType("float")
                        .HasColumnName("AUG");

                    b.Property<float?>("Dev")
                        .HasColumnType("float")
                        .HasColumnName("DEV");

                    b.Property<float?>("Feb")
                        .HasColumnType("float")
                        .HasColumnName("FEB");

                    b.Property<float?>("Jan")
                        .HasColumnType("float")
                        .HasColumnName("JAN");

                    b.Property<float?>("Jul")
                        .HasColumnType("float")
                        .HasColumnName("JUL");

                    b.Property<float?>("Jun")
                        .HasColumnType("float")
                        .HasColumnName("JUN");

                    b.Property<float?>("Mar")
                        .HasColumnType("float")
                        .HasColumnName("MAR");

                    b.Property<float?>("May")
                        .HasColumnType("float")
                        .HasColumnName("MAY");

                    b.Property<int?>("MeterReaderTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("METER_READER_TB_ID");

                    b.Property<float?>("Nov")
                        .HasColumnType("float")
                        .HasColumnName("NOV");

                    b.Property<float?>("Oct")
                        .HasColumnType("float")
                        .HasColumnName("OCT");

                    b.Property<float?>("Sep")
                        .HasColumnType("float")
                        .HasColumnName("SEP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MeterReaderTbId" }, "fk_ENERGY_MONTH_USAGE_TB_METER_READER_TB1_idx");

                    b.ToTable("energy_month_usage_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.EnergyUsageTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("MeterDt")
                        .HasColumnType("datetime")
                        .HasColumnName("METER_DT");

                    b.Property<int?>("MeterItemTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("METER_ITEM_TB_ID");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("UPDATE_USER");

                    b.Property<float?>("Usage")
                        .HasColumnType("float")
                        .HasColumnName("USAGE");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MeterItemTbId" }, "fk_ENERGY_USAGE_TB_METER_ITEM_TB1_idx");

                    b.ToTable("energy_usage_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.FloorTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<int?>("BuildingTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BUILDING_TB_ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingTbId" }, "fk_FLOOR_TB_BUILDING_TB1_idx");

                    b.ToTable("floor_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MaterialTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID")
                        .HasComment("자재 인덱스");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MATERIAL_CODE");

                    b.Property<string>("Mfr")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MFR")
                        .HasComment("제조사");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int")
                        .HasColumnName("PLACE_ID");

                    b.Property<int?>("SafeNum")
                        .HasColumnType("int(11)")
                        .HasColumnName("SAFE_NUM");

                    b.Property<string>("Standard")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("STANDARD");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TYPE");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UNIT");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("material_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterItemTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<float?>("AccumUsage")
                        .HasColumnType("float")
                        .HasColumnName("ACCUM_USAGE");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("MeterItem")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("METER_ITEM")
                        .HasComment("검침항목");

                    b.Property<int?>("MeterReaderTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("METER_READER_TB_ID");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MeterReaderTbId" }, "fk_METER_ITEM_TB_METER_READER_TB1_idx");

                    b.ToTable("meter_item_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterReaderTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<int?>("BuildingTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BUILDING_TB_ID");

                    b.Property<string>("Category")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("MeterItem")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("METER_ITEM");

                    b.Property<string>("Type")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("TYPE")
                        .HasComment("계약종별");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingTbId" }, "fk_METER_READER_TB_BUILDING_TB1_idx");

                    b.ToTable("meter_reader_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.PlaceTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("CancelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("CANCEL_DT");

                    b.Property<DateTime?>("ContractDt")
                        .HasColumnType("datetime")
                        .HasColumnName("CONTRACT_DT");

                    b.Property<string>("ContractNum")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CONTRACT_NUM");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTE");

                    b.Property<sbyte?>("PermBeauty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_BEAUTY")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermConstruct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_CONSTRUCT")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermEnergy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_ENERGY")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermFire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_FIRE")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermLift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_LIFT")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_MACHINE")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_MATERIAL")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermNetwrok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_NETWROK")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermSecurity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_SECURITY")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("PermVoc")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("PERM_VOC");

                    b.Property<string>("PlaceCd")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PLACE_CD");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Tel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TEL");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("place_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.RoomTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("FloorTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("FLOOR_TB_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FloorTbId" }, "fk_ROOM_TB_FLOOR_TB1_idx");

                    b.ToTable("room_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.StoreTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<int?>("BuildingTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BUILDING_TB_ID");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("MaterialTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("MATERIAL_TB_ID");

                    b.Property<int?>("Num")
                        .HasColumnType("int(11)")
                        .HasColumnName("NUM");

                    b.Property<float?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("PRICE")
                        .HasComment("금액\\n");

                    b.Property<int?>("RoomTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ROOM_TB_ID");

                    b.Property<float?>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("UNIT_PRICE")
                        .HasComment("단가\\n");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingTbId" }, "fk_STORE_TB_BUILDING_TB1_idx");

                    b.HasIndex(new[] { "MaterialTbId" }, "fk_STORE_TB_MATERIAL_TB1_idx");

                    b.HasIndex(new[] { "RoomTbId" }, "fk_STORE_TB_ROOM_TB1_idx");

                    b.ToTable("store_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.UnitTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PlaceTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PLACE_TB_ID");

                    b.Property<string>("Unit")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("UNIT");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("UPDATE_USER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlaceTbId" }, "fk_UNIT_PLACE_TB1_idx");

                    b.ToTable("unit_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.UserTb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    b.Property<sbyte?>("AdminYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ADMIN_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte?>("AlramYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ALRAM_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATE_USER");

                    b.Property<DateTime?>("DelDt")
                        .HasColumnType("datetime")
                        .HasColumnName("DEL_DT");

                    b.Property<string>("DelUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEL_USER");

                    b.Property<sbyte?>("DelYn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("DEL_YN")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Job")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("JOB");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<int?>("PermBasic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_BASIC")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermBeauty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_BEAUTY")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermConstruct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_CONSTRUCT")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermEnergy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_ENERGY")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermFire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_FIRE")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermLift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_LIFT")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_MACHINE")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_MATERIAL")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermNetwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_NETWORK")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermSecurity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_SECURITY")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_USER")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("PermVoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PERM_VOC")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("PlaceTbId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PLACE_TB_ID");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("UpdateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATE_DT")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATE_USER");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlaceTbId" }, "fk_USER_TB_PLACE_TB1_idx");

                    b.ToTable("user_tb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.AdminPlaceTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.AdminTb", "AdminTb")
                        .WithMany("AdminPlaceTbs")
                        .HasForeignKey("AdminTbId")
                        .HasConstraintName("fk_ADMIN_TB_has_PLACE_ADMIN_TB1");

                    b.HasOne("FamTec.Shared.Model.PlaceTb", "Place")
                        .WithMany("AdminPlaceTbs")
                        .HasForeignKey("PlaceId")
                        .HasConstraintName("fk_ADMIN_TB_has_PLACE_PLACE1");

                    b.Navigation("AdminTb");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("FamTec.Shared.Model.AdminTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.DepartmentTb", "DepartmentTb")
                        .WithMany("AdminTbs")
                        .HasForeignKey("DepartmentTbId")
                        .HasConstraintName("fk_ADMIN_TB_DEPARTMENT_TB1");

                    b.HasOne("FamTec.Shared.Model.UserTb", "UserTb")
                        .WithMany("AdminTbs")
                        .HasForeignKey("UserTbId")
                        .HasConstraintName("fk_ADMIN_TB_USER_TB");

                    b.Navigation("DepartmentTb");

                    b.Navigation("UserTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.BuildingTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.PlaceTb", "PlaceTb")
                        .WithMany("BuildingTbs")
                        .HasForeignKey("PlaceTbId")
                        .HasConstraintName("fk_BUILDING_TB_PLACE_TB1");

                    b.Navigation("PlaceTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.EnergyMonthUsageTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.MeterReaderTb", "MeterReaderTb")
                        .WithMany("EnergyMonthUsageTbs")
                        .HasForeignKey("MeterReaderTbId")
                        .HasConstraintName("fk_ENERGY_MONTH_USAGE_TB_METER_READER_TB1");

                    b.Navigation("MeterReaderTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.EnergyUsageTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.MeterItemTb", "MeterItemTb")
                        .WithMany("EnergyUsageTbs")
                        .HasForeignKey("MeterItemTbId")
                        .HasConstraintName("fk_ENERGY_USAGE_TB_METER_ITEM_TB1");

                    b.Navigation("MeterItemTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.FloorTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.BuildingTb", "BuildingTb")
                        .WithMany("FloorTbs")
                        .HasForeignKey("BuildingTbId")
                        .HasConstraintName("fk_FLOOR_TB_BUILDING_TB1");

                    b.Navigation("BuildingTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterItemTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.MeterReaderTb", "MeterReaderTb")
                        .WithMany("MeterItemTbs")
                        .HasForeignKey("MeterReaderTbId")
                        .HasConstraintName("fk_METER_ITEM_TB_METER_READER_TB1");

                    b.Navigation("MeterReaderTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterReaderTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.BuildingTb", "BuildingTb")
                        .WithMany("MeterReaderTbs")
                        .HasForeignKey("BuildingTbId")
                        .HasConstraintName("fk_METER_READER_TB_BUILDING_TB1");

                    b.Navigation("BuildingTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.RoomTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.FloorTb", "FloorTb")
                        .WithMany("RoomTbs")
                        .HasForeignKey("FloorTbId")
                        .HasConstraintName("fk_ROOM_TB_FLOOR_TB1");

                    b.Navigation("FloorTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.StoreTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.BuildingTb", "BuildingTb")
                        .WithMany("StoreTbs")
                        .HasForeignKey("BuildingTbId")
                        .HasConstraintName("fk_STORE_TB_BUILDING_TB1");

                    b.HasOne("FamTec.Shared.Model.MaterialTb", "MaterialTb")
                        .WithMany("StoreTbs")
                        .HasForeignKey("MaterialTbId")
                        .HasConstraintName("fk_STORE_TB_MATERIAL_TB1");

                    b.HasOne("FamTec.Shared.Model.RoomTb", "RoomTb")
                        .WithMany("StoreTbs")
                        .HasForeignKey("RoomTbId")
                        .HasConstraintName("fk_STORE_TB_ROOM_TB1");

                    b.Navigation("BuildingTb");

                    b.Navigation("MaterialTb");

                    b.Navigation("RoomTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.UnitTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.PlaceTb", "PlaceTb")
                        .WithMany("UnitTbs")
                        .HasForeignKey("PlaceTbId")
                        .HasConstraintName("fk_UNIT_PLACE_TB1");

                    b.Navigation("PlaceTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.UserTb", b =>
                {
                    b.HasOne("FamTec.Shared.Model.PlaceTb", "PlaceTb")
                        .WithMany("UserTbs")
                        .HasForeignKey("PlaceTbId")
                        .HasConstraintName("fk_USER_TB_PLACE_TB1");

                    b.Navigation("PlaceTb");
                });

            modelBuilder.Entity("FamTec.Shared.Model.AdminTb", b =>
                {
                    b.Navigation("AdminPlaceTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.BuildingTb", b =>
                {
                    b.Navigation("FloorTbs");

                    b.Navigation("MeterReaderTbs");

                    b.Navigation("StoreTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.DepartmentTb", b =>
                {
                    b.Navigation("AdminTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.FloorTb", b =>
                {
                    b.Navigation("RoomTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MaterialTb", b =>
                {
                    b.Navigation("StoreTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterItemTb", b =>
                {
                    b.Navigation("EnergyUsageTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.MeterReaderTb", b =>
                {
                    b.Navigation("EnergyMonthUsageTbs");

                    b.Navigation("MeterItemTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.PlaceTb", b =>
                {
                    b.Navigation("AdminPlaceTbs");

                    b.Navigation("BuildingTbs");

                    b.Navigation("UnitTbs");

                    b.Navigation("UserTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.RoomTb", b =>
                {
                    b.Navigation("StoreTbs");
                });

            modelBuilder.Entity("FamTec.Shared.Model.UserTb", b =>
                {
                    b.Navigation("AdminTbs");
                });
#pragma warning restore 612, 618
        }
    }
}
